#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_POKE_BALL 1
#define ITEM_GREAT_BALL 2
#define ITEM_ULTRA_BALL 3
#define ITEM_MASTER_BALL 4
#define ITEM_SAFARI_BALL 5

// Medicine
#define ITEM_POTION 6
#define ITEM_SUPER_POTION 7
#define ITEM_HYPER_POTION 8
#define ITEM_MAX_POTION 9
#define ITEM_FULL_RESTORE 10
#define ITEM_REVIVE 11
#define ITEM_MAX_REVIVE 12
#define ITEM_FRESH_WATER 13
#define ITEM_SODA_POP 14
#define ITEM_LEMONADE 15
#define ITEM_MOOMOO_MILK 16
#define ITEM_FULL_HEAL 17
#define ITEM_ETHER 18
#define ITEM_MAX_ETHER 19
#define ITEM_ELIXIR 20
#define ITEM_ELIXER ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR 21
#define ITEM_MAX_ELIXER ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE 22
#define ITEM_SACRED_ASH 23

// Regional Specialties
#define ITEM_LAVA_COOKIE 24

// Vitamins
#define ITEM_HP_UP 25
#define ITEM_PROTEIN 26
#define ITEM_IRON 27
#define ITEM_CALCIUM 28
#define ITEM_ZINC 29
#define ITEM_CARBOS 30
#define ITEM_PP_UP 31
#define ITEM_PP_MAX 32

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 33
#define ITEM_ABILITY_PATCH 34

// Candy
#define ITEM_RARE_CANDY 35

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 36
#define ITEM_YELLOW_FLUTE 37
#define ITEM_RED_FLUTE 38

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 39
#define ITEM_WHITE_FLUTE 40

// Encounter Modifiers
#define ITEM_REPEL 41
#define ITEM_SUPER_REPEL 42
#define ITEM_MAX_REPEL 43
#define ITEM_LURE 44
#define ITEM_SUPER_LURE 45
#define ITEM_MAX_LURE 46
#define ITEM_ESCAPE_ROPE 47

// Escape Items
#define ITEM_POKE_DOLL 48
#define ITEM_FLUFFY_TAIL 49
#define ITEM_POKE_TOY 50

#define ITEM_MAX_MUSHROOMS 51

// Treasures
#define ITEM_NUGGET 52
#define ITEM_TINY_MUSHROOM 53
#define ITEM_TINYMUSHROOM ITEM_TINY_MUSHROOM // Pre-Gen VI name
#define ITEM_BIG_MUSHROOM 54
#define ITEM_BALM_MUSHROOM 55
#define ITEM_BALMMUSHROOM ITEM_BALM_MUSHROOM // Pre-Gen VI name
#define ITEM_PEARL 56
#define ITEM_BIG_PEARL 57
#define ITEM_PEARL_STRING 58
#define ITEM_STARDUST 59
#define ITEM_STAR_PIECE 60
#define ITEM_COMET_SHARD 61
#define ITEM_SHOAL_SALT 62
#define ITEM_SHOAL_SHELL 63
#define ITEM_RED_SHARD 64
#define ITEM_BLUE_SHARD 65
#define ITEM_YELLOW_SHARD 66
#define ITEM_GREEN_SHARD 67
#define ITEM_HEART_SCALE 68
#define ITEM_HONEY 69
#define ITEM_RARE_BONE 70
#define ITEM_ODD_KEYSTONE 71
#define ITEM_PRETTY_FEATHER 72
#define ITEM_PRETTY_WING ITEM_PRETTY_FEATHER // Pre-Gen VIII name

// Fossils
#define ITEM_HELIX_FOSSIL 73
#define ITEM_DOME_FOSSIL 74
#define ITEM_OLD_AMBER 75
#define ITEM_ROOT_FOSSIL 76
#define ITEM_CLAW_FOSSIL 77
#define ITEM_ARMOR_FOSSIL 78
#define ITEM_SKULL_FOSSIL 79
#define ITEM_COVER_FOSSIL 80
#define ITEM_PLUME_FOSSIL 81

// Mulch
#define ITEM_GROWTH_MULCH 82
#define ITEM_DAMP_MULCH 83
#define ITEM_STABLE_MULCH 84
#define ITEM_GOOEY_MULCH 85
#define ITEM_RICH_MULCH 86
#define ITEM_SURPRISE_MULCH 87
#define ITEM_BOOST_MULCH 88
#define ITEM_AMAZE_MULCH 89

// Mail
#define ITEM_ORANGE_MAIL 90
#define ITEM_HARBOR_MAIL 91
#define ITEM_GLITTER_MAIL 92
#define ITEM_MECH_MAIL 93
#define ITEM_WOOD_MAIL 94
#define ITEM_WAVE_MAIL 95
#define ITEM_BEAD_MAIL 96
#define ITEM_SHADOW_MAIL 97
#define ITEM_TROPIC_MAIL 98
#define ITEM_DREAM_MAIL 99
#define ITEM_FAB_MAIL 100
#define ITEM_RETRO_MAIL 101

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define ITEM_FIRE_STONE 102
#define ITEM_WATER_STONE 103
#define ITEM_THUNDER_STONE 104
#define ITEM_THUNDERSTONE ITEM_THUNDER_STONE // Pre-Gen VI name
#define ITEM_LEAF_STONE 105
#define ITEM_ICE_STONE 106
#define ITEM_SUN_STONE 107
#define ITEM_MOON_STONE 108
#define ITEM_SHINY_STONE 109
#define ITEM_DUSK_STONE 110
#define ITEM_DAWN_STONE 111
#define ITEM_DRAGON_SCALE 112
#define ITEM_UPGRADE 113
#define ITEM_UP_GRADE ITEM_UPGRADE // Pre-Gen VIII name
#define ITEM_PROTECTOR 114
#define ITEM_ELECTIRIZER 115
#define ITEM_MAGMARIZER 116
#define ITEM_DUBIOUS_DISC 117
#define ITEM_REAPER_CLOTH 118
#define ITEM_PRISM_SCALE 119
#define ITEM_OVAL_STONE 120

#define ITEM_EVERSTONE 121

// Drives
#define ITEM_DOUSE_DRIVE 122
#define ITEM_SHOCK_DRIVE 123
#define ITEM_BURN_DRIVE 124
#define ITEM_CHILL_DRIVE 125

// Colored Orbs
#define ITEM_RED_ORB 126
#define ITEM_BLUE_ORB 127

// Gems
#define ITEM_NORMAL_GEM 128

// Species-specific Held Items
#define ITEM_LIGHT_BALL 129
#define ITEM_LEEK 130
#define ITEM_STICK ITEM_LEEK // Pre-Gen VIII name
#define ITEM_THICK_CLUB 131
#define ITEM_LUCKY_PUNCH 132
#define ITEM_METAL_POWDER 133
#define ITEM_QUICK_POWDER 134
#define ITEM_DEEP_SEA_SCALE 135
#define ITEM_DEEPSEASCALE ITEM_DEEP_SEA_SCALE // Pre-Gen VI name
#define ITEM_DEEP_SEA_TOOTH 136
#define ITEM_DEEPSEATOOTH ITEM_DEEP_SEA_TOOTH // Pre-Gen VI name
#define ITEM_SOUL_DEW 137
#define ITEM_ADAMANT_ORB 138
#define ITEM_LUSTROUS_ORB 139
#define ITEM_GRISEOUS_ORB 140

// Contest Scarves
#define ITEM_RED_SCARF 141
#define ITEM_BLUE_SCARF 142
#define ITEM_PINK_SCARF 143
#define ITEM_GREEN_SCARF 144
#define ITEM_YELLOW_SCARF 145

// Type-boosting Held Items
#define ITEM_SILK_SCARF 146
#define ITEM_CHARCOAL 147
#define ITEM_MYSTIC_WATER 148
#define ITEM_MAGNET 149
#define ITEM_MIRACLE_SEED 150
#define ITEM_NEVER_MELT_ICE 151
#define ITEM_NEVERMELTICE ITEM_NEVER_MELT_ICE // Pre-Gen VI name
#define ITEM_BLACK_BELT 152
#define ITEM_BLACKBELT ITEM_BLACK_BELT // Gen II name
#define ITEM_POISON_BARB 153
#define ITEM_SOFT_SAND 154
#define ITEM_SHARP_BEAK 155
#define ITEM_TWISTED_SPOON 156
#define ITEM_TWISTEDSPOON ITEM_TWISTED_SPOON // Pre-Gen VI name
#define ITEM_SILVER_POWDER 157
#define ITEM_SILVERPOWDER ITEM_SILVER_POWDER // Pre-Gen VI name
#define ITEM_HARD_STONE 158
#define ITEM_SPELL_TAG 159
#define ITEM_DRAGON_FANG 160
#define ITEM_BLACK_GLASSES 161
#define ITEM_BLACKGLASSES ITEM_BLACK_GLASSES // Pre-Gen VI name
#define ITEM_METAL_COAT 162

// Choice Items
#define ITEM_CHOICE_BAND 163
#define ITEM_CHOICE_SPECS 164
#define ITEM_CHOICE_SCARF 165

// Status Orbs
#define ITEM_FLAME_ORB 166
#define ITEM_TOXIC_ORB 167

// Weather Rocks
#define ITEM_DAMP_ROCK 168
#define ITEM_HEAT_ROCK 169
#define ITEM_SMOOTH_ROCK 170
#define ITEM_ICY_ROCK 171

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 172
#define ITEM_PSYCHIC_SEED 173
#define ITEM_MISTY_SEED 174
#define ITEM_GRASSY_SEED 175

// Type-activated Stat Modifiers
#define ITEM_ABSORB_BULB 176
#define ITEM_CELL_BATTERY 177
#define ITEM_LUMINOUS_MOSS 178
#define ITEM_SNOWBALL 179

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 180
#define ITEM_BRIGHTPOWDER ITEM_BRIGHT_POWDER // Pre-Gen VI name
#define ITEM_WHITE_HERB 181
#define ITEM_EXP_SHARE 182
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW 183
#define ITEM_SOOTHE_BELL 184
#define ITEM_MENTAL_HERB 185
#define ITEM_KINGS_ROCK 186
#define ITEM_AMULET_COIN 187
#define ITEM_CLEANSE_TAG 188
#define ITEM_SMOKE_BALL 189
#define ITEM_FOCUS_BAND 190
#define ITEM_LUCKY_EGG 191
#define ITEM_SCOPE_LENS 192
#define ITEM_LEFTOVERS 193
#define ITEM_SHELL_BELL 194
#define ITEM_WIDE_LENS 195
#define ITEM_MUSCLE_BAND 196
#define ITEM_WISE_GLASSES 197
#define ITEM_EXPERT_BELT 198
#define ITEM_LIGHT_CLAY 199
#define ITEM_LIFE_ORB 200
#define ITEM_POWER_HERB 201
#define ITEM_FOCUS_SASH 202
#define ITEM_ZOOM_LENS 203
#define ITEM_METRONOME 204
#define ITEM_IRON_BALL 205
#define ITEM_LAGGING_TAIL 206
#define ITEM_DESTINY_KNOT 207
#define ITEM_BLACK_SLUDGE 208
#define ITEM_GRIP_CLAW 209
#define ITEM_STICKY_BARB 210
#define ITEM_SHED_SHELL 211
#define ITEM_BIG_ROOT 212
#define ITEM_RAZOR_CLAW 213
#define ITEM_RAZOR_FANG 214
#define ITEM_EVIOLITE 215
#define ITEM_FLOAT_STONE 216
#define ITEM_ROCKY_HELMET 217
#define ITEM_AIR_BALLOON 218
#define ITEM_RED_CARD 219
#define ITEM_RING_TARGET 220
#define ITEM_BINDING_BAND 221
#define ITEM_EJECT_BUTTON 222
#define ITEM_WEAKNESS_POLICY 223
#define ITEM_ASSAULT_VEST 224
#define ITEM_SAFETY_GOGGLES 225
#define ITEM_ADRENALINE_ORB 226
#define ITEM_TERRAIN_EXTENDER 227
#define ITEM_PROTECTIVE_PADS 228
#define ITEM_THROAT_SPRAY 229
#define ITEM_EJECT_PACK 230
#define ITEM_HEAVY_DUTY_BOOTS 231
#define ITEM_BLUNDER_POLICY 232
#define ITEM_ROOM_SERVICE 233
#define ITEM_UTILITY_UMBRELLA 234
#define ITEM_ABILITY_SHIELD 235
#define ITEM_CLEAR_AMULET 236
#define ITEM_PUNCHING_GLOVE 237
#define ITEM_COVERT_CLOAK 238
#define ITEM_LOADED_DICE 239

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define ITEM_CHERI_BERRY 240
#define ITEM_CHESTO_BERRY 241
#define ITEM_PECHA_BERRY 242
#define ITEM_RAWST_BERRY 243
#define ITEM_ASPEAR_BERRY 244
#define ITEM_LEPPA_BERRY 245
#define ITEM_ORAN_BERRY 246
#define ITEM_PERSIM_BERRY 247
#define ITEM_LUM_BERRY 248
#define ITEM_SITRUS_BERRY 249
#define ITEM_FIGY_BERRY 250
#define ITEM_WIKI_BERRY 251
#define ITEM_MAGO_BERRY 252
#define ITEM_AGUAV_BERRY 253
#define ITEM_IAPAPA_BERRY 254
#define ITEM_RAZZ_BERRY 255
#define ITEM_BLUK_BERRY 256
#define ITEM_NANAB_BERRY 257
#define ITEM_PINAP_BERRY 258
#define ITEM_POMEG_BERRY 259
#define ITEM_KELPSY_BERRY 260
#define ITEM_QUALOT_BERRY 261
#define ITEM_HONDEW_BERRY 262
#define ITEM_GREPA_BERRY 263
#define ITEM_TAMATO_BERRY 264
#define ITEM_CHILAN_BERRY 265
#define ITEM_OCCA_BERRY 266
#define ITEM_PASSHO_BERRY 267
#define ITEM_WACAN_BERRY 268
#define ITEM_RINDO_BERRY 269
#define ITEM_YACHE_BERRY 270
#define ITEM_CHOPLE_BERRY 271
#define ITEM_KEBIA_BERRY 272
#define ITEM_SHUCA_BERRY 273
#define ITEM_COBA_BERRY 274
#define ITEM_PAYAPA_BERRY 275
#define ITEM_TANGA_BERRY 276
#define ITEM_CHARTI_BERRY 277
#define ITEM_KASIB_BERRY 278
#define ITEM_HABAN_BERRY 279
#define ITEM_COLBUR_BERRY 280
#define ITEM_BABIRI_BERRY 281
#define ITEM_ROSELI_BERRY 282
#define ITEM_LIECHI_BERRY 283
#define ITEM_GANLON_BERRY 284
#define ITEM_SALAC_BERRY 285
#define ITEM_PETAYA_BERRY 286
#define ITEM_APICOT_BERRY 287
#define ITEM_LANSAT_BERRY 288
#define ITEM_STARF_BERRY 289
#define ITEM_ENIGMA_BERRY 290
#define ITEM_MICLE_BERRY 291
#define ITEM_CUSTAP_BERRY 292
#define ITEM_JABOCA_BERRY 293
#define ITEM_ROWAP_BERRY 294
#define ITEM_KEE_BERRY 295
#define ITEM_MARANGA_BERRY 296
#define ITEM_ENIGMA_BERRY_E_READER 297

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TM01 298
#define ITEM_TM02 299
#define ITEM_TM03 300
#define ITEM_TM04 301
#define ITEM_TM05 302
#define ITEM_TM06 303
#define ITEM_TM07 304
#define ITEM_TM08 305
#define ITEM_TM09 306
#define ITEM_TM10 307
#define ITEM_TM11 308
#define ITEM_TM12 309
#define ITEM_TM13 310
#define ITEM_TM14 311
#define ITEM_TM15 312
#define ITEM_TM16 313
#define ITEM_TM17 314
#define ITEM_TM18 315
#define ITEM_TM19 316
#define ITEM_TM20 317
#define ITEM_TM21 318
#define ITEM_TM22 319
#define ITEM_TM23 320
#define ITEM_TM24 321
#define ITEM_TM25 322
#define ITEM_TM26 323
#define ITEM_TM27 324
#define ITEM_TM28 325
#define ITEM_TM29 326
#define ITEM_TM30 327
#define ITEM_TM31 328
#define ITEM_TM32 329
#define ITEM_TM33 330
#define ITEM_TM34 331
#define ITEM_TM35 332
#define ITEM_TM36 333
#define ITEM_TM37 334
#define ITEM_TM38 335
#define ITEM_TM39 336
#define ITEM_TM40 337
#define ITEM_TM41 338
#define ITEM_TM42 339
#define ITEM_TM43 340
#define ITEM_TM44 341
#define ITEM_TM45 342
#define ITEM_TM46 343
#define ITEM_TM47 344
#define ITEM_TM48 345
#define ITEM_TM49 346
#define ITEM_TM50 347
#define ITEM_TM51 348
#define ITEM_TM52 349
#define ITEM_TM53 350
#define ITEM_TM54 351
#define ITEM_TM55 352
#define ITEM_TM56 353
#define ITEM_TM57 354
#define ITEM_TM58 355
#define ITEM_TM59 356
#define ITEM_TM60 357
#define ITEM_TM61 358
#define ITEM_TM62 359
#define ITEM_TM63 360
#define ITEM_TM64 361
#define ITEM_TM65 362
#define ITEM_TM66 363
#define ITEM_TM67 364
#define ITEM_TM68 365
#define ITEM_TM69 366
#define ITEM_TM70 367
#define ITEM_TM71 368
#define ITEM_TM72 369
#define ITEM_TM74 370
#define ITEM_TM75 371
#define ITEM_TM76 372
#define ITEM_TM77 373
#define ITEM_TM78 374
#define ITEM_TM79 375
#define ITEM_TM80 376
#define ITEM_TM81 377
#define ITEM_TM82 378
#define ITEM_TM83 379
#define ITEM_TM84 380
#define ITEM_TM85 381
#define ITEM_TM86 382
#define ITEM_TM87 383
#define ITEM_TM88 384
#define ITEM_TM89 385
#define ITEM_TM90 386
#define ITEM_TM91 387
#define ITEM_TM92 388
#define ITEM_TM93 389
#define ITEM_TM94 390
#define ITEM_TM95 391
#define ITEM_TM96 392
#define ITEM_TM97 393
#define ITEM_TM98 394
#define ITEM_TM99 395
#define ITEM_TM100 396
#define ITEM_TM101 397
#define ITEM_TM102 398
#define ITEM_TM103 399
#define ITEM_TM104 400
#define ITEM_TM105 401
#define ITEM_TM106 402
#define ITEM_TM107 403
#define ITEM_TM108 404
#define ITEM_TM109 405
#define ITEM_TM110 406
#define ITEM_TM111 407
#define ITEM_TM112 408
#define ITEM_TM113 409
#define ITEM_TM114 410
#define ITEM_TM115 411
#define ITEM_TM116 412
#define ITEM_TM117 413
#define ITEM_TM118 414
#define ITEM_TM119 415
#define ITEM_TM120 416
#define ITEM_TM121 417
#define ITEM_TM122 418
#define ITEM_TM123 419
#define ITEM_TM124 420
#define ITEM_TM125 421
#define ITEM_TM126 422
#define ITEM_TM127 423
#define ITEM_TM128 424
#define ITEM_TM129 425
#define ITEM_TM130 426
#define ITEM_TM131 427
#define ITEM_TM132 428
#define ITEM_TM133 429
#define ITEM_TM134 430
#define ITEM_TM135 431
#define ITEM_TM136 432
#define ITEM_TM137 433
#define ITEM_TM138 434
#define ITEM_TM139 435
#define ITEM_TM140 436
#define ITEM_TM141 437
#define ITEM_TM142 438
#define ITEM_TM143 439
#define ITEM_TM144 440
#define ITEM_TM145 441
#define ITEM_TM146 442
#define ITEM_TM148 443
#define ITEM_TM149 444
#define ITEM_TM150 445

#define ITEM_HM01 448
#define ITEM_HM02 449
#define ITEM_HM03 450
#define ITEM_HM04 451
#define ITEM_HM05 452
#define ITEM_HM06 453
#define ITEM_HM07 454
#define ITEM_HM08 455

// Charms
#define ITEM_OVAL_CHARM 456
#define ITEM_SHINY_CHARM 457
#define ITEM_CATCHING_CHARM 458
#define ITEM_EXP_CHARM 459

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 460
#define ITEM_GRACIDEA 461
#define ITEM_DNA_SPLICERS 462

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 463
#define ITEM_Z_POWER_RING 464
#define ITEM_DYNAMAX_BAND 465

// Misc. Key Items
#define ITEM_BICYCLE 466
#define ITEM_MACH_BIKE 467
#define ITEM_ACRO_BIKE 468
#define ITEM_OLD_ROD 469
#define ITEM_GOOD_ROD 470
#define ITEM_SUPER_ROD 471
#define ITEM_DOWSING_MACHINE 472
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP 473
#define ITEM_VS_SEEKER 474
#define ITEM_TM_CASE 475
#define ITEM_BERRY_POUCH 476
#define ITEM_POKEMON_BOX_LINK 477
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 478
#define ITEM_POWDER_JAR 479
#define ITEM_WAILMER_PAIL 480
#define ITEM_POKE_RADAR 481
#define ITEM_POKEBLOCK_CASE 482
#define ITEM_SOOT_SACK 483
#define ITEM_POKE_FLUTE 484
#define ITEM_FAME_CHECKER 485
#define ITEM_TEACHY_TV 486

// Story Key Items
#define ITEM_SS_TICKET 487
#define ITEM_EON_TICKET 488
#define ITEM_MYSTIC_TICKET 489
#define ITEM_AURORA_TICKET 490
#define ITEM_OLD_SEA_MAP 491
#define ITEM_LETTER 492
#define ITEM_DEVON_PARTS 493
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 494
#define ITEM_DEVON_SCOPE 495
#define ITEM_BASEMENT_KEY 496
#define ITEM_SCANNER 497
#define ITEM_STORAGE_KEY 498
#define ITEM_KEY_TO_ROOM_1 499
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 500
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 501
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 502
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 503
#define ITEM_MAGMA_EMBLEM 504
#define ITEM_CONTEST_PASS 505
#define ITEM_PARCEL 506
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY 507
#define ITEM_BIKE_VOUCHER 508
#define ITEM_CARD_KEY 509
#define ITEM_LIFT_KEY 510
#define ITEM_SILPH_SCOPE 511
#define ITEM_TRI_PASS 512
#define ITEM_RAINBOW_PASS 513
#define ITEM_TEA 514
#define ITEM_RUBY 515
#define ITEM_SAPPHIRE 516

// GEN IX ITEMS
#define ITEM_BOOSTER_ENERGY 517
#define ITEM_MIRROR_HERB 518
#define ITEM_TERA_ORB 519

#define ITEM_ADAMANT_CRYSTAL 520
#define ITEM_GRISEOUS_CORE 522
#define ITEM_LUSTROUS_GLOBE 523

#define ITEM_FAIRY_FEATHER 524
#define ITEM_STELLAR_TERA_SHARD 525

#define ITEM_STRANGE_BALL 526

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT 527
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_TAMATO_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_TAMATO_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 100
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11
#define EFFECT_ITEM_USE_POKE_FLUTE          12

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
