#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define ITEM_POKE_BALL 1
#define ITEM_GREAT_BALL 2
#define ITEM_ULTRA_BALL 3
#define ITEM_MASTER_BALL 4
#define ITEM_SAFARI_BALL 5

// Medicine
#define ITEM_POTION 6
#define ITEM_SUPER_POTION 7
#define ITEM_HYPER_POTION 8
#define ITEM_MAX_POTION 9
#define ITEM_FULL_RESTORE 10
#define ITEM_REVIVE 11
#define ITEM_MAX_REVIVE 12
#define ITEM_FULL_HEAL 13
#define ITEM_ETHER 14
#define ITEM_MAX_ETHER 15
#define ITEM_ELIXIR 16
#define ITEM_ELIXER ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR 17
#define ITEM_MAX_ELIXER ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE 18

// Regional Specialties
#define ITEM_LAVA_COOKIE 19

// Vitamins
#define ITEM_HP_UP 20
#define ITEM_PROTEIN 21
#define ITEM_IRON 22
#define ITEM_CALCIUM 23
#define ITEM_ZINC 24
#define ITEM_CARBOS 25
#define ITEM_PP_UP 26
#define ITEM_PP_MAX 27

// Ability Modifiers
#define ITEM_ABILITY_CAPSULE 28
#define ITEM_ABILITY_PATCH 29

// Candy
#define ITEM_RARE_CANDY 30

// Medicinal Flutes
#define ITEM_BLUE_FLUTE 31
#define ITEM_YELLOW_FLUTE 32
#define ITEM_RED_FLUTE 33

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE 34
#define ITEM_WHITE_FLUTE 35

// Encounter Modifiers
#define ITEM_REPEL 36
#define ITEM_SUPER_REPEL 37
#define ITEM_MAX_REPEL 38
#define ITEM_ESCAPE_ROPE 39

// Escape Items
#define ITEM_FLUFFY_TAIL 40

// Treasures
#define ITEM_NUGGET 41
#define ITEM_PEARL 42
#define ITEM_BIG_PEARL 43
#define ITEM_STARDUST 44
#define ITEM_STAR_PIECE 45
#define ITEM_SHOAL_SALT 46
#define ITEM_SHOAL_SHELL 47
#define ITEM_RED_SHARD 48
#define ITEM_BLUE_SHARD 49
#define ITEM_YELLOW_SHARD 50
#define ITEM_GREEN_SHARD 51
#define ITEM_HEART_SCALE 52

// Fossils
#define ITEM_HELIX_FOSSIL 53
#define ITEM_DOME_FOSSIL 54
#define ITEM_OLD_AMBER 55
#define ITEM_ROOT_FOSSIL 56
#define ITEM_CLAW_FOSSIL 57
#define ITEM_ARMOR_FOSSIL 58
#define ITEM_SKULL_FOSSIL 59
#define ITEM_COVER_FOSSIL 60
#define ITEM_PLUME_FOSSIL 61

// Mulch
#define ITEM_GROWTH_MULCH 62

// Mail
#define ITEM_HARBOR_MAIL 63

#define FIRST_MAIL_INDEX ITEM_HARBOR_MAIL

// Evolution Items
#define ITEM_FIRE_STONE 64
#define ITEM_WATER_STONE 65
#define ITEM_THUNDER_STONE 66
#define ITEM_THUNDERSTONE ITEM_THUNDER_STONE // Pre-Gen VI name
#define ITEM_LEAF_STONE 67
#define ITEM_ICE_STONE 68
#define ITEM_SUN_STONE 69
#define ITEM_MOON_STONE 70
#define ITEM_SHINY_STONE 71
#define ITEM_DUSK_STONE 72
#define ITEM_DAWN_STONE 73
#define ITEM_DRAGON_SCALE 74
#define ITEM_UPGRADE 75
#define ITEM_UP_GRADE ITEM_UPGRADE // Pre-Gen VIII name
#define ITEM_PROTECTOR 76
#define ITEM_ELECTIRIZER 77
#define ITEM_MAGMARIZER 78
#define ITEM_DUBIOUS_DISC 79
#define ITEM_REAPER_CLOTH 80
#define ITEM_PRISM_SCALE 81
#define ITEM_OVAL_STONE 82

#define ITEM_EVERSTONE 83

// Drives
#define ITEM_DOUSE_DRIVE 84
#define ITEM_SHOCK_DRIVE 85
#define ITEM_BURN_DRIVE 86
#define ITEM_CHILL_DRIVE 87

// Colored Orbs
#define ITEM_RED_ORB 88
#define ITEM_BLUE_ORB 89

// Gems
#define ITEM_NORMAL_GEM 90

// Species-specific Held Items
#define ITEM_LIGHT_BALL 91
#define ITEM_LEEK 92
#define ITEM_STICK ITEM_LEEK // Pre-Gen VIII name
#define ITEM_THICK_CLUB 93
#define ITEM_LUCKY_PUNCH 94
#define ITEM_METAL_POWDER 95
#define ITEM_QUICK_POWDER 96
#define ITEM_DEEP_SEA_SCALE 97
#define ITEM_DEEPSEASCALE ITEM_DEEP_SEA_SCALE // Pre-Gen VI name
#define ITEM_DEEP_SEA_TOOTH 98
#define ITEM_DEEPSEATOOTH ITEM_DEEP_SEA_TOOTH // Pre-Gen VI name
#define ITEM_SOUL_DEW 99
#define ITEM_ADAMANT_ORB 100
#define ITEM_LUSTROUS_ORB 101
#define ITEM_GRISEOUS_ORB 102

// Contest Scarves
#define ITEM_RED_SCARF 103
#define ITEM_BLUE_SCARF 104
#define ITEM_PINK_SCARF 105
#define ITEM_GREEN_SCARF 106
#define ITEM_YELLOW_SCARF 107

// Type-boosting Held Items
#define ITEM_SILK_SCARF 108
#define ITEM_CHARCOAL 109
#define ITEM_MYSTIC_WATER 110
#define ITEM_MAGNET 111
#define ITEM_MIRACLE_SEED 112
#define ITEM_NEVER_MELT_ICE 113
#define ITEM_NEVERMELTICE ITEM_NEVER_MELT_ICE // Pre-Gen VI name
#define ITEM_BLACK_BELT 114
#define ITEM_BLACKBELT ITEM_BLACK_BELT // Gen II name
#define ITEM_POISON_BARB 115
#define ITEM_SOFT_SAND 116
#define ITEM_SHARP_BEAK 117
#define ITEM_TWISTED_SPOON 118
#define ITEM_TWISTEDSPOON ITEM_TWISTED_SPOON // Pre-Gen VI name
#define ITEM_SILVER_POWDER 119
#define ITEM_SILVERPOWDER ITEM_SILVER_POWDER // Pre-Gen VI name
#define ITEM_HARD_STONE 120
#define ITEM_SPELL_TAG 121
#define ITEM_DRAGON_FANG 122
#define ITEM_BLACK_GLASSES 123
#define ITEM_BLACKGLASSES ITEM_BLACK_GLASSES // Pre-Gen VI name
#define ITEM_METAL_COAT 124

// Choice Items
#define ITEM_CHOICE_BAND 125
#define ITEM_CHOICE_SPECS 126
#define ITEM_CHOICE_SCARF 127

// Status Orbs
#define ITEM_FLAME_ORB 128
#define ITEM_TOXIC_ORB 129

// Weather Rocks
#define ITEM_DAMP_ROCK 130
#define ITEM_HEAT_ROCK 131
#define ITEM_SMOOTH_ROCK 132
#define ITEM_ICY_ROCK 133

// Terrain Seeds
#define ITEM_ELECTRIC_SEED 134
#define ITEM_PSYCHIC_SEED 135
#define ITEM_MISTY_SEED 136
#define ITEM_GRASSY_SEED 137

// Misc. Held Items
#define ITEM_BRIGHT_POWDER 138
#define ITEM_BRIGHTPOWDER ITEM_BRIGHT_POWDER // Pre-Gen VI name
#define ITEM_WHITE_HERB 139
#define ITEM_EXP_SHARE 140
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW 141
#define ITEM_SOOTHE_BELL 142
#define ITEM_MENTAL_HERB 143
#define ITEM_KINGS_ROCK 144
#define ITEM_AMULET_COIN 145
#define ITEM_CLEANSE_TAG 146
#define ITEM_SMOKE_BALL 147
#define ITEM_FOCUS_BAND 148
#define ITEM_LUCKY_EGG 149
#define ITEM_SCOPE_LENS 150
#define ITEM_LEFTOVERS 151
#define ITEM_SHELL_BELL 152
#define ITEM_WIDE_LENS 153
#define ITEM_MUSCLE_BAND 154
#define ITEM_WISE_GLASSES 155
#define ITEM_EXPERT_BELT 156
#define ITEM_LIGHT_CLAY 157
#define ITEM_LIFE_ORB 158
#define ITEM_POWER_HERB 159
#define ITEM_FOCUS_SASH 160
#define ITEM_ZOOM_LENS 161
#define ITEM_METRONOME 162
#define ITEM_IRON_BALL 163
#define ITEM_LAGGING_TAIL 164
#define ITEM_DESTINY_KNOT 165
#define ITEM_BLACK_SLUDGE 166
#define ITEM_GRIP_CLAW 167
#define ITEM_STICKY_BARB 168
#define ITEM_SHED_SHELL 169
#define ITEM_BIG_ROOT 170
#define ITEM_RAZOR_CLAW 171
#define ITEM_RAZOR_FANG 172
#define ITEM_EVIOLITE 173
#define ITEM_FLOAT_STONE 174
#define ITEM_ROCKY_HELMET 175
#define ITEM_AIR_BALLOON 176
#define ITEM_RED_CARD 177
#define ITEM_BINDING_BAND 178
#define ITEM_EJECT_BUTTON 179
#define ITEM_WEAKNESS_POLICY 180
#define ITEM_ASSAULT_VEST 181
#define ITEM_SAFETY_GOGGLES 182
#define ITEM_TERRAIN_EXTENDER 183
#define ITEM_PROTECTIVE_PADS 184
#define ITEM_THROAT_SPRAY 185
#define ITEM_EJECT_PACK 186
#define ITEM_HEAVY_DUTY_BOOTS 187
#define ITEM_BLUNDER_POLICY 188
#define ITEM_ROOM_SERVICE 189
#define ITEM_UTILITY_UMBRELLA 190
#define ITEM_ABILITY_SHIELD 191
#define ITEM_CLEAR_AMULET 192
#define ITEM_PUNCHING_GLOVE 193
#define ITEM_COVERT_CLOAK 194
#define ITEM_LOADED_DICE 195

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define ITEM_CHERI_BERRY 196
#define ITEM_CHESTO_BERRY 197
#define ITEM_PECHA_BERRY 198
#define ITEM_RAWST_BERRY 199
#define ITEM_ASPEAR_BERRY 200
#define ITEM_LEPPA_BERRY 201
#define ITEM_ORAN_BERRY 202
#define ITEM_PERSIM_BERRY 203
#define ITEM_LUM_BERRY 204
#define ITEM_SITRUS_BERRY 205
#define ITEM_CHILAN_BERRY 206
#define ITEM_OCCA_BERRY 207
#define ITEM_PASSHO_BERRY 208
#define ITEM_WACAN_BERRY 209
#define ITEM_RINDO_BERRY 210
#define ITEM_YACHE_BERRY 211
#define ITEM_CHOPLE_BERRY 212
#define ITEM_KEBIA_BERRY 213
#define ITEM_SHUCA_BERRY 214
#define ITEM_COBA_BERRY 215
#define ITEM_PAYAPA_BERRY 216
#define ITEM_TANGA_BERRY 217
#define ITEM_CHARTI_BERRY 218
#define ITEM_KASIB_BERRY 219
#define ITEM_HABAN_BERRY 220
#define ITEM_COLBUR_BERRY 221
#define ITEM_BABIRI_BERRY 222
#define ITEM_ROSELI_BERRY 223
#define ITEM_LIECHI_BERRY 224
#define ITEM_GANLON_BERRY 225
#define ITEM_SALAC_BERRY 226
#define ITEM_PETAYA_BERRY 227
#define ITEM_APICOT_BERRY 228
#define ITEM_LANSAT_BERRY 229
#define ITEM_STARF_BERRY 230
#define ITEM_MICLE_BERRY 231
#define ITEM_CUSTAP_BERRY 232
#define ITEM_JABOCA_BERRY 233
#define ITEM_ROWAP_BERRY 234
#define ITEM_KEE_BERRY 235
#define ITEM_MARANGA_BERRY 236
#define ITEM_ENIGMA_BERRY_E_READER 237

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define ITEM_TM01 238
#define ITEM_TM02 239
#define ITEM_TM03 240
#define ITEM_TM04 241
#define ITEM_TM05 242
#define ITEM_TM06 243
#define ITEM_TM07 244
#define ITEM_TM08 245
#define ITEM_TM09 246
#define ITEM_TM10 247
#define ITEM_TM11 248
#define ITEM_TM12 249
#define ITEM_TM13 250
#define ITEM_TM14 251
#define ITEM_TM15 252
#define ITEM_TM16 253
#define ITEM_TM17 254
#define ITEM_TM18 255
#define ITEM_TM19 256
#define ITEM_TM20 257
#define ITEM_TM21 258
#define ITEM_TM22 259
#define ITEM_TM23 260
#define ITEM_TM24 261
#define ITEM_TM25 262
#define ITEM_TM26 263
#define ITEM_TM27 264
#define ITEM_TM28 265
#define ITEM_TM29 266
#define ITEM_TM30 267
#define ITEM_TM31 268
#define ITEM_TM32 269
#define ITEM_TM33 270
#define ITEM_TM34 271
#define ITEM_TM35 272
#define ITEM_TM36 273
#define ITEM_TM37 274
#define ITEM_TM38 275
#define ITEM_TM39 276
#define ITEM_TM40 277
#define ITEM_TM41 278
#define ITEM_TM42 279
#define ITEM_TM43 280
#define ITEM_TM44 281
#define ITEM_TM45 282
#define ITEM_TM46 283
#define ITEM_TM47 284
#define ITEM_TM48 285
#define ITEM_TM49 286
#define ITEM_TM50 287
#define ITEM_TM51 288
#define ITEM_TM52 289
#define ITEM_TM53 290
#define ITEM_TM54 291
#define ITEM_TM55 292
#define ITEM_TM56 293
#define ITEM_TM57 294
#define ITEM_TM58 295
#define ITEM_TM59 296
#define ITEM_TM60 297
#define ITEM_TM61 298
#define ITEM_TM62 299
#define ITEM_TM63 300
#define ITEM_TM64 301
#define ITEM_TM65 302
#define ITEM_TM66 303
#define ITEM_TM67 304
#define ITEM_TM68 305
#define ITEM_TM69 306
#define ITEM_TM70 307
#define ITEM_TM71 308
#define ITEM_TM72 309
#define ITEM_TM74 310
#define ITEM_TM75 311
#define ITEM_TM76 312
#define ITEM_TM77 313
#define ITEM_TM78 314
#define ITEM_TM79 315
#define ITEM_TM80 316
#define ITEM_TM81 317
#define ITEM_TM82 318
#define ITEM_TM83 319
#define ITEM_TM84 320
#define ITEM_TM85 321
#define ITEM_TM86 322
#define ITEM_TM87 323
#define ITEM_TM88 324
#define ITEM_TM89 325
#define ITEM_TM90 326
#define ITEM_TM91 327
#define ITEM_TM92 328
#define ITEM_TM93 329
#define ITEM_TM94 330
#define ITEM_TM95 331
#define ITEM_TM96 332
#define ITEM_TM97 333
#define ITEM_TM98 334
#define ITEM_TM99 335
#define ITEM_TM100 336
#define ITEM_TM101 337
#define ITEM_TM102 338
#define ITEM_TM103 339
#define ITEM_TM104 340
#define ITEM_TM105 341
#define ITEM_TM106 342
#define ITEM_TM107 343
#define ITEM_TM108 344
#define ITEM_TM109 345
#define ITEM_TM110 346
#define ITEM_TM111 347
#define ITEM_TM112 348
#define ITEM_TM113 349
#define ITEM_TM114 350
#define ITEM_TM115 351
#define ITEM_TM116 352
#define ITEM_TM117 353
#define ITEM_TM118 354
#define ITEM_TM119 355
#define ITEM_TM120 356
#define ITEM_TM121 357
#define ITEM_TM122 358
#define ITEM_TM123 359
#define ITEM_TM124 360
#define ITEM_TM125 361
#define ITEM_TM126 362
#define ITEM_TM127 363
#define ITEM_TM128 364
#define ITEM_TM129 365
#define ITEM_TM130 366
#define ITEM_TM131 367
#define ITEM_TM132 368
#define ITEM_TM133 369
#define ITEM_TM134 370
#define ITEM_TM135 371
#define ITEM_TM136 372
#define ITEM_TM137 373
#define ITEM_TM138 374
#define ITEM_TM139 375
#define ITEM_TM140 376
#define ITEM_TM141 377
#define ITEM_TM142 378
#define ITEM_TM143 379
#define ITEM_TM144 380
#define ITEM_TM145 381
#define ITEM_TM146 382
#define ITEM_TM148 383
#define ITEM_TM149 384
#define ITEM_TM150 385

#define ITEM_HM01 388
#define ITEM_HM02 389
#define ITEM_HM03 391
#define ITEM_HM04 392
#define ITEM_HM05 393
#define ITEM_HM06 394
#define ITEM_HM07 395
#define ITEM_HM08 396

// Form-changing Key Items
#define ITEM_ROTOM_CATALOG 397
#define ITEM_DNA_SPLICERS 398

// Battle Mechanic Key Items
#define ITEM_MEGA_RING 399
#define ITEM_Z_POWER_RING 400
#define ITEM_DYNAMAX_BAND 401

// Misc. Key Items
#define ITEM_MACH_BIKE 402
#define ITEM_ACRO_BIKE 403
#define ITEM_OLD_ROD 404
#define ITEM_GOOD_ROD 405
#define ITEM_SUPER_ROD 406
#define ITEM_VS_SEEKER 407
#define ITEM_TM_CASE 408
#define ITEM_BERRY_POUCH 409
#define ITEM_POKEMON_BOX_LINK 410
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE 411
#define ITEM_WAILMER_PAIL 412
#define ITEM_POKEBLOCK_CASE 413
#define ITEM_SOOT_SACK 414

// Story Key Items
#define ITEM_EON_TICKET 415
#define ITEM_MYSTIC_TICKET 416
#define ITEM_AURORA_TICKET 417
#define ITEM_OLD_SEA_MAP 418
#define ITEM_LETTER 419
#define ITEM_DEVON_PARTS 420
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES 421
#define ITEM_DEVON_SCOPE 422
#define ITEM_BASEMENT_KEY 423
#define ITEM_SCANNER 424
#define ITEM_STORAGE_KEY 425
#define ITEM_KEY_TO_ROOM_1 426
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 427
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 428
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 429
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE 430
#define ITEM_MAGMA_EMBLEM 431
#define ITEM_CONTEST_PASS 432

// GEN IX ITEMS
#define ITEM_MIRROR_HERB 433
#define ITEM_TERA_ORB 434

#define ITEM_ADAMANT_CRYSTAL 435
#define ITEM_GRISEOUS_CORE 436
#define ITEM_LUSTROUS_GLOBE 437

#define ITEM_FAIRY_FEATHER 438

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT 439
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_SITRUS_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_SITRUS_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_SITRUS_BERRY
#define LAST_KIRI_BERRY               ITEM_SITRUS_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_SITRUS_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_SITRUS_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId) (((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId) ((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 150
#define NUM_HIDDEN_MACHINES 8

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1


// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11
#define EFFECT_ITEM_USE_POKE_FLUTE          12

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
