#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                          0
#define TRAINER_SAWYER                        1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1          2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2          3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3          4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4          5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1       6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2       7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3       8
#define TRAINER_GABRIELLE                     9
#define TRAINER_GRUNT_PETALBURG_WOODS        10
#define TRAINER_MARCEL                       11
#define TRAINER_ALBERTO                      12
#define TRAINER_ED                           13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4      14
#define TRAINER_DECLAN                       15
#define TRAINER_GRUNT_RUSTURF_TUNNEL         16
#define TRAINER_GRUNT_WEATHER_INST_1         17
#define TRAINER_GRUNT_WEATHER_INST_2         18
#define TRAINER_GRUNT_WEATHER_INST_3         19
#define TRAINER_GRUNT_MUSEUM_1               20
#define TRAINER_GRUNT_MUSEUM_2               21
#define TRAINER_GRUNT_SPACE_CENTER_1         22
#define TRAINER_GRUNT_MT_PYRE_1              23
#define TRAINER_GRUNT_MT_PYRE_2              24
#define TRAINER_GRUNT_MT_PYRE_3              25
#define TRAINER_GRUNT_WEATHER_INST_4         26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5         27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6         28
#define TRAINER_FREDRICK                     29
#define TRAINER_MATTIAS                      30
#define TRAINER_ZANDER                       31
#define TRAINER_SHELLY_WEATHER_INSTITUTE     32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN       33
#define TRAINER_ARCHIE                       34
#define TRAINER_LEAH                         35
#define TRAINER_DAISY                        36
#define TRAINER_ROSE                         37
#define TRAINER_FELIX                        38
#define TRAINER_VIOLET                       39
#define TRAINER_DUSTY                        40
#define TRAINER_CHIP                         41
#define TRAINER_FOSTER                       42
#define TRAINER_GABBY_AND_TY                 43
#define TRAINER_GABBY_AND_TY_6               44
#define TRAINER_LOLA                         45
#define TRAINER_AUSTINA                      46
#define TRAINER_GWEN                         47
#define TRAINER_RICKY                        48
#define TRAINER_SIMON                        49
#define TRAINER_CHARLIE                      50
#define TRAINER_RANDALL                      51
#define TRAINER_PARKER                       52
#define TRAINER_GEORGE                       53
#define TRAINER_GRUNT_A                      54
#define TRAINER_GRUNT_B                      55
#define TRAINER_GRUNT_C                      56
#define TRAINER_GRUNT_D                      57
#define TRAINER_GRUNT_E                      58
#define TRAINER_BERKE                        74
#define TRAINER_BRAXTON                      75
#define TRAINER_VINCENT                      76
#define TRAINER_LEROY                        77
#define TRAINER_WILTON                       78
#define TRAINER_EDGAR                        79
#define TRAINER_ALBERT                       80
#define TRAINER_SAMMY                        81
#define TRAINER_VITO                         82
#define TRAINER_OWEN                         83
#define TRAINER_WARREN                       88
#define TRAINER_MARY                         89
#define TRAINER_ALEXIA                       90
#define TRAINER_JODY                         91
#define TRAINER_WENDY                        92
#define TRAINER_KEIRA                        93
#define TRAINER_BROOKE                       94
#define TRAINER_JENNIFER                     95
#define TRAINER_HOPE                         96
#define TRAINER_SHANNON                      97
#define TRAINER_MICHELLE                     98
#define TRAINER_CAROLINE                     99
#define TRAINER_JULIE                       100
#define TRAINER_PATRICIA                    105
#define TRAINER_KINDRA                      106
#define TRAINER_TAMMY                       107
#define TRAINER_VALERIE                     108
#define TRAINER_TASHA                       109
#define TRAINER_CINDY                       114
#define TRAINER_DAPHNE                      115
#define TRAINER_GRUNT_SPACE_CENTER_2        116
#define TRAINER_BRIANNA                     118
#define TRAINER_NAOMI                       119
#define TRAINER_MELISSA                     124
#define TRAINER_SHEILA                      125
#define TRAINER_SHIRLEY                     126
#define TRAINER_JESSICA                     127
#define TRAINER_CONNIE                      128
#define TRAINER_BRIDGET                     129
#define TRAINER_OLIVIA                      130
#define TRAINER_TIFFANY                     131
#define TRAINER_WINSTON                     136
#define TRAINER_MOLLIE                      137
#define TRAINER_GARRET                      138
#define TRAINER_STEVE                       143
#define TRAINER_THALIA                      144
#define TRAINER_MARK                        145
#define TRAINER_GRUNT_MT_CHIMNEY_1          146
#define TRAINER_LUIS                        151
#define TRAINER_DOMINIK                     152
#define TRAINER_DOUGLAS                     153
#define TRAINER_DARRIN                      154
#define TRAINER_TONY                        155
#define TRAINER_JEROME                      156
#define TRAINER_MATTHEW                     157
#define TRAINER_DAVID                       158
#define TRAINER_SPENCER                     159
#define TRAINER_ROLAND                      160
#define TRAINER_NOLEN                       161
#define TRAINER_STAN                        162
#define TRAINER_BARRY                       163
#define TRAINER_DEAN                        164
#define TRAINER_RODNEY                      165
#define TRAINER_RICHARD                     166
#define TRAINER_HERMAN                      167
#define TRAINER_SANTIAGO                    168
#define TRAINER_GILBERT                     169
#define TRAINER_FRANKLIN                    170
#define TRAINER_KEVIN                       171
#define TRAINER_JACK                        172
#define TRAINER_DUDLEY                      173
#define TRAINER_CHAD                        174
#define TRAINER_TAKAO                       179
#define TRAINER_HITOSHI                     180
#define TRAINER_KIYO                        181
#define TRAINER_KOICHI                      182
#define TRAINER_NOB                         183
#define TRAINER_YUJI                        188
#define TRAINER_DAISUKE                     189
#define TRAINER_ATSUSHI                     190
#define TRAINER_KIRK                        191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        193
#define TRAINER_SHAWN                       194
#define TRAINER_FERNANDO                    195
#define TRAINER_DALTON                      196
#define TRAINER_COLE                        201
#define TRAINER_JEFF                        202
#define TRAINER_AXLE                        203
#define TRAINER_JACE                        204
#define TRAINER_KEEGAN                      205
#define TRAINER_BERNIE                      206
#define TRAINER_DREW                        211
#define TRAINER_BEAU                        212
#define TRAINER_LARRY                       213
#define TRAINER_SHANE                       214
#define TRAINER_JUSTIN                      215
#define TRAINER_ETHAN                       216
#define TRAINER_AUTUMN                      217
#define TRAINER_TRAVIS                      218
#define TRAINER_BRENT                       223
#define TRAINER_DONALD                      224
#define TRAINER_TAYLOR                      225
#define TRAINER_JEFFREY                     226
#define TRAINER_DEREK                       227
#define TRAINER_EDWARD                      232
#define TRAINER_PRESTON                     233
#define TRAINER_VIRGIL                      234
#define TRAINER_BLAKE                       235
#define TRAINER_WILLIAM                     236
#define TRAINER_JOSHUA                      237
#define TRAINER_CAMERON                     238
#define TRAINER_JACLYN                      243
#define TRAINER_HANNAH                      244
#define TRAINER_SAMANTHA                    245
#define TRAINER_MAURA                       246
#define TRAINER_KAYLA                       247
#define TRAINER_ALEXIS                      248
#define TRAINER_JACKI                       249
#define TRAINER_WALTER                      254
#define TRAINER_MICAH                       255
#define TRAINER_THOMAS                      256
#define TRAINER_MATT                        261
#define TRAINER_OZ                          262
#define TRAINER_DIEGO                       263
#define TRAINER_DRAKE                       264
#define TRAINER_ROXANNE                     265
#define TRAINER_BRAWLY                      266
#define TRAINER_SAM                         267
#define TRAINER_FLANNERY                    268
#define TRAINER_NORMAN                      269
#define TRAINER_WINONA                      270
#define TRAINER_TATE_AND_LIZA               271
#define TRAINER_JUAN                        272
#define TRAINER_JERRY                       273
#define TRAINER_TED                         274
#define TRAINER_PAUL                        275
#define TRAINER_KAREN                       280
#define TRAINER_GEORGIA                     281
#define TRAINER_KATE_AND_JOY                286
#define TRAINER_ANNA_AND_MEG                287
#define TRAINER_VICTOR                      292
#define TRAINER_MIGUEL                      293
#define TRAINER_COLTON                      294
#define TRAINER_VICTORIA                    299
#define TRAINER_VANESSA                     300
#define TRAINER_BETHANY                     301
#define TRAINER_ISABEL                      302
#define TRAINER_TIMOTHY                     307
#define TRAINER_VICKY                       312
#define TRAINER_SHELBY                      313
#define TRAINER_CALVIN                      318
#define TRAINER_BILLY                       319
#define TRAINER_JOSH                        320
#define TRAINER_TOMMY                       321
#define TRAINER_JOEY                        322
#define TRAINER_BEN                         323
#define TRAINER_QUINCY                      324
#define TRAINER_KATELYNN                    325
#define TRAINER_JAYLEN                      326
#define TRAINER_DILLON                      327
#define TRAINER_EDDIE                       332
#define TRAINER_ALLEN                       333
#define TRAINER_TIMMY                       334
#define TRAINER_FATTY                       335
#define TRAINER_ANDREW                      336
#define TRAINER_IVAN                        337
#define TRAINER_CLAUDE                      338
#define TRAINER_ELLIOT                      339
#define TRAINER_NED                         340
#define TRAINER_DALE                        341
#define TRAINER_NOLAN                       342
#define TRAINER_BARNY                       343
#define TRAINER_WADE                        344
#define TRAINER_CARTER                      345
#define TRAINER_RONALD                      350
#define TRAINER_JACOB                       351
#define TRAINER_ANTHONY                     352
#define TRAINER_BENJAMIN                    353
#define TRAINER_ABIGAIL                     358
#define TRAINER_JASMINE                     359
#define TRAINER_DYLAN                       364
#define TRAINER_MARIA                       369
#define TRAINER_CAMDEN                      374
#define TRAINER_DEMETRIUS                   375
#define TRAINER_ISAIAH                      376
#define TRAINER_PABLO                       377
#define TRAINER_CHASE                       378
#define TRAINER_ISOBEL                      383
#define TRAINER_DONNY                       384
#define TRAINER_TALIA                       385
#define TRAINER_KATELYN                     386
#define TRAINER_ALLISON                     387
#define TRAINER_NICOLAS                     392
#define TRAINER_AARON                       397
#define TRAINER_PERRY                       398
#define TRAINER_HUGH                        399
#define TRAINER_PHIL                        400
#define TRAINER_JARED                       401
#define TRAINER_HUMBERTO                    402
#define TRAINER_PRESLEY                     403
#define TRAINER_EDWARDO                     404
#define TRAINER_COLIN                       405
#define TRAINER_ROBERT                      406
#define TRAINER_BENNY                       407
#define TRAINER_CHESTER                     408
#define TRAINER_ALEX                        413
#define TRAINER_BECK                        414
#define TRAINER_YASU                        415
#define TRAINER_TAKASHI                     416
#define TRAINER_DIANNE                      417
#define TRAINER_JANI                        418
#define TRAINER_LAO                         419
#define TRAINER_LUNG                        420
#define TRAINER_JOCELYN                     425
#define TRAINER_LAURA                       426
#define TRAINER_CYNDY                       427
#define TRAINER_CORA                        428
#define TRAINER_PAULA                       429
#define TRAINER_MADELINE                    434
#define TRAINER_CLARISSA                    435
#define TRAINER_ANGELICA                    436
#define TRAINER_BEVERLY                     441
#define TRAINER_IMANI                       442
#define TRAINER_KYLA                        443
#define TRAINER_DENISE                      444
#define TRAINER_BETH                        445
#define TRAINER_TARA                        446
#define TRAINER_MISSY                       447
#define TRAINER_ALICE                       448
#define TRAINER_JENNY                       449
#define TRAINER_GRACE                       450
#define TRAINER_TANYA                       451
#define TRAINER_SHARON                      452
#define TRAINER_NIKKI                       453
#define TRAINER_BRENDA                      454
#define TRAINER_KATIE                       455
#define TRAINER_SUSIE                       456
#define TRAINER_KARA                        457
#define TRAINER_DANA                        458
#define TRAINER_SIENNA                      459
#define TRAINER_DEBRA                       460
#define TRAINER_LINDA                       461
#define TRAINER_KAYLEE                      462
#define TRAINER_LAUREL                      463
#define TRAINER_CARLEE                      464
#define TRAINER_HEIDI                       469
#define TRAINER_BECKY                       470
#define TRAINER_CAROL                       471
#define TRAINER_NANCY                       472
#define TRAINER_MARTHA                      473
#define TRAINER_DIANA                       474
#define TRAINER_CEDRIC                      475
#define TRAINER_IRENE                       476
#define TRAINER_AMY_AND_LIV                 481
#define TRAINER_GINA_AND_MIA                483
#define TRAINER_MIU_AND_YUKI                484
#define TRAINER_HUEY                        490
#define TRAINER_EDMOND                      491
#define TRAINER_ERNEST                      492
#define TRAINER_DWAYNE                      493
#define TRAINER_PHILLIP                     494
#define TRAINER_LEONARD                     495
#define TRAINER_DUNCAN                      496
#define TRAINER_ELI                         501
#define TRAINER_ANNIKA                      502
#define TRAINER_JAZMYN                      503
#define TRAINER_JONAS                       504
#define TRAINER_KAYLEY                      505
#define TRAINER_AURON                       506
#define TRAINER_KELVIN                      507
#define TRAINER_MARLEY                      508
#define TRAINER_REYNA                       509
#define TRAINER_HUDSON                      510
#define TRAINER_CONOR                       511
#define TRAINER_EDWIN                       512
#define TRAINER_HECTOR                      513
#define TRAINER_TABITHA_MOSSDEEP            514
#define TRAINER_WALLY_VR_1                  519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_119           522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   523
#define TRAINER_BRENDAN_ROUTE_110           524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   528
#define TRAINER_MAY_ROUTE_103_MUDKIP        529
#define TRAINER_MAY_ROUTE_110_MUDKIP        530
#define TRAINER_MAY_ROUTE_119_MUDKIP        531
#define TRAINER_MAY_ROUTE_103_TREECKO       532
#define TRAINER_MAY_ROUTE_110_TREECKO       533
#define TRAINER_MAY_ROUTE_119_TREECKO       534
#define TRAINER_MAY_ROUTE_103_TORCHIC       535
#define TRAINER_MAY_ROUTE_110_TORCHIC       536
#define TRAINER_MAY_ROUTE_119_TORCHIC       537
#define TRAINER_ISAAC                       538
#define TRAINER_DAVIS                       539
#define TRAINER_MITCHELL                    540
#define TRAINER_LYDIA                       545
#define TRAINER_HALLE                       546
#define TRAINER_GARRISON                    547
#define TRAINER_JACKSON                     552
#define TRAINER_LORENZO                     553
#define TRAINER_SEBASTIAN                   554
#define TRAINER_CATHERINE                   559
#define TRAINER_JENNA                       560
#define TRAINER_SOPHIA                      561
#define TRAINER_JULIO                       566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     567
#define TRAINER_GRUNT_UNUSED                568
#define TRAINER_GRUNT_MT_PYRE_4             569
#define TRAINER_GRUNT_JAGGED_PASS           570
#define TRAINER_MARC                        571
#define TRAINER_BRENDEN                     572
#define TRAINER_LILITH                      573
#define TRAINER_CRISTIAN                    574
#define TRAINER_SYLVIA                      575
#define TRAINER_LEONARDO                    576
#define TRAINER_ATHENA                      577
#define TRAINER_HARRISON                    578
#define TRAINER_GRUNT_MT_CHIMNEY_2          579
#define TRAINER_CLARENCE                    580
#define TRAINER_TERRY                       581
#define TRAINER_NATE                        582
#define TRAINER_KATHLEEN                    583
#define TRAINER_CLIFFORD                    584
#define TRAINER_NICHOLAS                    585
#define TRAINER_GRUNT_SPACE_CENTER_3        586
#define TRAINER_GRUNT_SPACE_CENTER_4        587
#define TRAINER_GRUNT_SPACE_CENTER_5        588
#define TRAINER_GRUNT_SPACE_CENTER_6        589
#define TRAINER_GRUNT_SPACE_CENTER_7        590
#define TRAINER_MACEY                       591
#define TRAINER_BRENDAN_RUSTBORO            592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     593
#define TRAINER_PAXTON                      594
#define TRAINER_ISABELLA                    595
#define TRAINER_GRUNT_WEATHER_INST_5        596
#define TRAINER_TABITHA_MT_CHIMNEY          597
#define TRAINER_JONATHAN                    598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    599
#define TRAINER_MAY_RUSTBORO_MUDKIP         600
#define TRAINER_MAXIE_MAGMA_HIDEOUT         601
#define TRAINER_MAXIE_MT_CHIMNEY            602
#define TRAINER_TIANA                       603
#define TRAINER_HALEY                       604
#define TRAINER_JANICE                      605
#define TRAINER_VIVI                        606
#define TRAINER_SALLY                       611
#define TRAINER_ROBIN                       612
#define TRAINER_ANDREA                      613
#define TRAINER_CRISSY                      614
#define TRAINER_RICK                        615
#define TRAINER_LYLE                        616
#define TRAINER_JOSE                        617
#define TRAINER_DOUG                        618
#define TRAINER_GREG                        619
#define TRAINER_KENT                        620
#define TRAINER_JAMES                       621
#define TRAINER_BRICE                       626
#define TRAINER_TRENT                       627
#define TRAINER_LENNY                       628
#define TRAINER_LUCAS                       629
#define TRAINER_ALAN                        630
#define TRAINER_CLARK                       631
#define TRAINER_ERIC                        632
#define TRAINER_MIKE                        634
#define TRAINER_DEZ_AND_LUKE                640
#define TRAINER_LEA_AND_JED                 641
#define TRAINER_KIRA_AND_DAN                642
#define TRAINER_JOHANNA                     647
#define TRAINER_GERALD                      648
#define TRAINER_VIVIAN                      649
#define TRAINER_DANIELLE                    650
#define TRAINER_HIDEO                       651
#define TRAINER_KEIGO                       652
#define TRAINER_RILEY                       653
#define TRAINER_FLINT                       654
#define TRAINER_ASHLEY                      655
#define TRAINER_WALLY_MAUVILLE              656
#define TRAINER_WALLY_VR_2                  657
#define TRAINER_WALLY_VR_3                  658
#define TRAINER_WALLY_VR_4                  659
#define TRAINER_WALLY_VR_5                  660
#define TRAINER_BRENDAN_LILYCOVE            661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    663
#define TRAINER_MAY_LILYCOVE_MUDKIP         664
#define TRAINER_MAY_LILYCOVE_TREECKO        665
#define TRAINER_MAY_LILYCOVE_TORCHIC        666
#define TRAINER_JONAH                       667
#define TRAINER_HENRY                       668
#define TRAINER_ROGER                       669
#define TRAINER_ALEXA                       670
#define TRAINER_RUBEN                       671
#define TRAINER_KOJI                        672
#define TRAINER_WAYNE                       673
#define TRAINER_AIDAN                       674
#define TRAINER_REED                        675
#define TRAINER_TISHA                       676
#define TRAINER_TORI_AND_TIA                677
#define TRAINER_KIM_AND_IRIS                678
#define TRAINER_TYRA_AND_IVY                679
#define TRAINER_MEL_AND_PAUL                680
#define TRAINER_JOHN_AND_JAY                681
#define TRAINER_RELI_AND_IAN                686
#define TRAINER_LILA_AND_ROY                687
#define TRAINER_LISA_AND_RAY                692
#define TRAINER_CHRIS                       693
#define TRAINER_DAWSON                      694
#define TRAINER_SARAH                       695
#define TRAINER_DARIAN                      696
#define TRAINER_HAILEY                      697
#define TRAINER_CHANDLER                    698
#define TRAINER_KALEB                       699
#define TRAINER_JOSEPH                      700
#define TRAINER_ALYSSA                      701
#define TRAINER_MARCOS                      702
#define TRAINER_RHETT                       703
#define TRAINER_TYRON                       704
#define TRAINER_CELINA                      705
#define TRAINER_BIANCA                      706
#define TRAINER_HAYDEN                      707
#define TRAINER_SOPHIE                      708
#define TRAINER_COBY                        709
#define TRAINER_LAWRENCE                    710
#define TRAINER_WYATT                       711
#define TRAINER_ANGELINA                    712
#define TRAINER_KAI                         713
#define TRAINER_CHARLOTTE                   714
#define TRAINER_DEANDRE                     715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      731
#define TRAINER_TABITHA_MAGMA_HIDEOUT       732
#define TRAINER_DARCY                       733
#define TRAINER_MAXIE_MOSSDEEP              734
#define TRAINER_PETE                        735
#define TRAINER_ISABELLE                    736
#define TRAINER_ANDRES                      737
#define TRAINER_JOSUE                       738
#define TRAINER_CAMRON                      739
#define TRAINER_CORY                        740
#define TRAINER_CAROLINA                    741
#define TRAINER_ELIJAH                      742
#define TRAINER_CELIA                       743
#define TRAINER_BRYAN                       744
#define TRAINER_BRANDEN                     745
#define TRAINER_BRYANT                      746
#define TRAINER_SHAYLA                      747
#define TRAINER_KYRA                        748
#define TRAINER_JAIDEN                      749
#define TRAINER_ALIX                        750
#define TRAINER_HELENE                      751
#define TRAINER_MARLENE                     752
#define TRAINER_DEVAN                       753
#define TRAINER_JOHNSON                     754
#define TRAINER_MELINA                      755
#define TRAINER_BRANDI                      756
#define TRAINER_AISHA                       757
#define TRAINER_MAKAYLA                     758
#define TRAINER_FABIAN                      759
#define TRAINER_DAYTON                      760
#define TRAINER_RACHEL                      761
#define TRAINER_LEONEL                      762
#define TRAINER_CALLIE                      763
#define TRAINER_CALE                        764
#define TRAINER_MYLES                       765
#define TRAINER_PAT                         766
#define TRAINER_CRISTIN                     767
#define TRAINER_MAY_RUSTBORO_TREECKO        768
#define TRAINER_MAY_RUSTBORO_TORCHIC        769
#define TRAINER_WINONA_2                    790
#define TRAINER_WINONA_3                    791
#define TRAINER_WINONA_4                    792
#define TRAINER_WINONA_5                    793
#define TRAINER_TATE_AND_LIZA_2             794
#define TRAINER_TATE_AND_LIZA_3             795
#define TRAINER_TATE_AND_LIZA_4             796
#define TRAINER_TATE_AND_LIZA_5             797
#define TRAINER_JUAN_2                      798
#define TRAINER_JUAN_3                      799
#define TRAINER_JUAN_4                      800
#define TRAINER_JUAN_5                      801
#define TRAINER_ANGELO                      802
#define TRAINER_DARIUS                      803
#define TRAINER_STEVEN                      804
#define TRAINER_ANABEL                      805
#define TRAINER_TUCKER                      806
#define TRAINER_SPENSER                     807
#define TRAINER_GRETA                       808
#define TRAINER_NOLAND                      809
#define TRAINER_LUCY                        810
#define TRAINER_BRANDON                     811
#define TRAINER_ANDRES_2                    812
#define TRAINER_ANDRES_3                    813
#define TRAINER_ANDRES_4                    814
#define TRAINER_ANDRES_5                    815
#define TRAINER_CORY_2                      816
#define TRAINER_CORY_3                      817
#define TRAINER_CORY_4                      818
#define TRAINER_CORY_5                      819
#define TRAINER_MARIELA                     848
#define TRAINER_ALVARO                      849
#define TRAINER_EVERETT                     850
#define TRAINER_RED                         851
#define TRAINER_LEAF                        852
#define TRAINER_BRENDAN_PLACEHOLDER         853
#define TRAINER_MAY_PLACEHOLDER             854

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      855
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
