#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(IRON_HEAD) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HEAVY_SLAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(STEEL_BEAM) \
    F(SCALD) \
    F(SOLAR_BEAM) \
    F(FLIP_TURN) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(LIQUIDATION) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(ALLURING_VOICE) \
    F(HYDRO_PUMP) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT)\
    F(STRUGGLE_BUG) \
    F(U_TURN)\
    F(NASTY_PLOT) \
    F(KNOCK_OFF) \
    F(THROAT_CHOP) \
    F(DARK_PULSE) \
    F(DRAGON_DANCE) \
    F(DRAGON_PULSE) \
    F(DRACO_METEOR) \
    F(VOLT_SWITCH) \
    F(THUNDER_PUNCH)\
    F(DAZZLING_GLEAM) \
    F(PLAY_ROUGH) \
    F(DRAINING_KISS) \
    F(DRAIN_PUNCH) \
    F(BODY_PRESS) \
    F(AURA_SPHERE) \
    F(CLOSE_COMBAT) \
    F(HEAT_CRASH) \
    F(FIRE_PUNCH) \
    F(WILL_O_WISP) \
    F(ACROBATICS) \
    F(TAILWIND) \
    F(HURRICANE) \
    F(CONFUSE_RAY) \
    F(HEX) \
    F(SHADOW_CLAW) \
    F(SEED_BOMB) \
    F(GRASS_KNOT) \
    F(STOMPING_TANTRUM) \
    F(SPIKES) \
    F(HIGH_HORSEPOWER) \
    F(SCORCHING_SANDS) \
    F(ICE_PUNCH) \
    F(HAZE) \
    F(WEATHER_BALL) \
    F(SWORDS_DANCE) \
    F(SUBSTITUTE) \
    F(HYPER_VOICE) \
    F(ENCORE) \
    F(BATON_PASS) \
    F(VENOSHOCK) \
    F(TOXIC_SPIKES) \
    F(GUNK_SHOT) \
    F(TRICK_ROOM) \
    F(PSYSHOCK) \
    F(ZEN_HEADBUTT) \
    F(STEALTH_ROCK) \
    F(STONE_EDGE) \
    F(FLASH_CANNON) 
        
#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
