gText_Birch_Welcome::
	.string "Welcome to my romhack!\p"
	.string "You'll find POKEMON from\n"
	.string "the first 5 gens.\p"
	.string "This will be difficult,\n"
	.string "But enjoy the fun times!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I used this Jirachi to wish\p"
	.string "that I could finish the ROM.\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Hopefully you know what a\n"
	.string "POKéMON is before playing\l"
	.string "or this will be too hard.\p"
	.string "This game was a fun way\n"
	.string "for me to learn to code while\l"
	.string "getting to do art and music.\p"
	.string "I appreciate you playing this\n"
	.string "and please look at the guides.\p"
	.string "Every gen 1-5 Pokemon is avaliable\n"
	.string "although some legendaries are rare.\p"
	.string "If you want one in particular,\n"
	.string "check the encounter guides!\p"
	.string "Prepare for a challenge!\l"
	.string "And I'll see you in Ever Grande City.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Gamer!$"

gText_Birch_BoyOrGirl::
	.string "Pick girl or the story breaks.\n"
	.string "So are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Make sure you're a girl.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's lass {PLAYER}-chan?$"

gText_Birch_YourePlayer::
	.string "Nice!\p"
	.string "You're {PLAYER}-chan who's accepted\n"
	.string "my challenge.\p"
	.string "Good luck!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\p"
	.string "$"
