AeroBase_3F_MapScripts::
	.byte 0

TrainerHill_EventScript_Grunt8::
	trainerbattle_single TRAINER_AEROGRUNT_8, TrainerHill_GruntIntro, TrainerHill_GruntDefeat
	msgbox TrainerHill_GruntPost, MSGBOX_AUTOCLOSE
	end

TrainerHill_EventScript_Grunt9::
	trainerbattle_single TRAINER_AEROGRUNT_9, TrainerHill_GruntIntro2, TrainerHill_GruntDefeat2
	msgbox TrainerHill_GruntPost2, MSGBOX_AUTOCLOSE
	end

TrainerHill_EventScript_Grunt10::
	trainerbattle_single TRAINER_AEROGRUNT_10, TrainerHill_GruntIntro, TrainerHill_GruntDefeat
	msgbox TrainerHill_GruntPost, MSGBOX_AUTOCLOSE
	end

TrainerHill_EventScript_Grunt11::
	trainerbattle_single TRAINER_AEROGRUNT_11, TrainerHill_GruntIntro2, TrainerHill_GruntDefeat2
	msgbox TrainerHill_GruntPost2, MSGBOX_AUTOCLOSE
	end
